#!/bin/env perl

use strict ; use warnings ;
use JSON ;

undef $/ ;
my $json = <STDIN> ;
my $graph = from_json $json ;

# 	graph =>
# 		{
# 		A =>
# 			{
# 			name => 'A',
# 			edges => ['B', 'C'],
# 			neighbours => ['B', 'C', 'D'],
# 			position => [3, 4],
# 			}
# 		}

my $object_type = ($ARGV[0]//'') eq 'box' ? 'new_box' : 'new_text' ;

my $script = "use App::Asciio::Scripting ;\n" ;
$script .= "select_all_elements ;\n" ;
$script .= "delete_selected_elements ;\n" ;

for my $node (values $graph->%*)
	{
	my $position = $node->{position} ;
	my $node_name = $node->{name} ;

	$script .= sprintf "add '%s', $object_type(TEXT_ONLY =>'%s'), %d, %d ;\n", $node_name, $node_name, $position->[0], $position->[1] ;
	}

print $script ;


# print to_json $graphs ;


#vim: set ft=perl :
