#!/bin/env perl

use strict ; use warnings ;
use JSON ;

undef $/ ;
my $json = <STDIN> ;
my $graphs = from_json $json ;

# my $graphs = 
# 	{
# 	graph =>
# 		{
# 		A =>
# 			{
# 			name => 'A',
# 			edges => ['B', 'C'],
# 			neighbours => ['B', 'C', 'D'],
# 			position => [3, 4],
# 			}
# 		}
# 	} ;

my $object_type = ($ARGV[0]//'') eq 'box' ? 'new_box' : 'new_text' ;

for my $graph (values $graphs->%*)
	{
	my $script = "use App::Asciio::Scripting ;\n" ;
	
	for my $node (values $graph->%*)
		{
		my $position = $node->{position} ;
		my $node_name = $node->{name} ;

		$script .= sprintf "add '%s', $object_type(TEXT_ONLY =>'%s'), %d, %d ;\n", $node_name, $node_name, $position->[0], $position->[1] ;
		}
	
	$script .= "print to_ascii ;\n" ;

	eval $script ;
	}


# print to_json $graphs ;


#vim: set ft=perl :
